name: Update Papers - AdEX

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  fetch-papers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Use the latest version of Python

      - name: Install dependencies
        run: |
          pip install lxml
          pip install nameparser
          pip install python-dateutil
          pip install requests
          pip install arxiv

      - name: Run script to fetch papers
        run: python papers/fetch_papers_adex.py

      - name: Commit and push changes
        run: |
          git config --local user.email "peter.lorenz.work@gmail.com"
          git config --local user.name "Peter Lorenz"
          git add assets/json/adex_papers.json
          git commit -m "Update adex papers.json" || echo "No changes to commit"
          git push
